Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/GuardClause:
  Enabled: false

AllCops:
  Exclude:
    - "spec/**/*"

Naming/HeredocDelimiterNaming:
  Enabled: false
